# This file was generated by GoReleaser. DO NOT EDIT.
cask "apifox-cli" do
  version "1.3.1"

  on_macos do
    on_intel do
      sha256 "bc7fb94e68124c2186cacb351e41d964ecc6220d294305c2017e7661ec1c56c8"
      url "https://github.com/iwen-conf/apifox-mcp/releases/download/v#{version}/apifox-cli_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "85a02349da0dae7fae4d0db7268e875c782413e347d2d7a8f9d056297ba58256"
      url "https://github.com/iwen-conf/apifox-mcp/releases/download/v#{version}/apifox-cli_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "aae0dcdb943f06009cc955fc988a86682ba2bfe84d0bec85ebcaf6a29158991c"
      url "https://github.com/iwen-conf/apifox-mcp/releases/download/v#{version}/apifox-cli_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "f45ccb731cadb0952c3513090ae20602ead6f1d367183f87a281e1cd2900a7d8"
      url "https://github.com/iwen-conf/apifox-mcp/releases/download/v#{version}/apifox-cli_#{version}_linux_arm64.tar.gz"
    end
  end

  name "apifox-cli"
  desc "Go CLI for AI-authored Apifox/OpenAPI documentation"
  homepage "https://github.com/iwen-conf/apifox-mcp"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "apifox-cli"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr",
        args: ["-d", "com.apple.quarantine", "#{staged_path}/apifox-cli"],
        sudo: false,
        must_succeed: false
    end
  end

  # No zap stanza required

end
