# This file was generated by GoReleaser. DO NOT EDIT.
cask "apifox-mcp" do
  version "1.2.0"

  on_macos do
    on_intel do
      sha256 "98345f238dfd02c9641689f41465cc87c473effefc10e7f41c55515caa6f11e4"
      url "https://github.com/iwen-conf/apifox-mcp/releases/download/v#{version}/apifox-mcp_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "5d5d1e6f7dd9d23df52aa7ca24925f730f8efbf6847d79a8408213622e1a1c1a"
      url "https://github.com/iwen-conf/apifox-mcp/releases/download/v#{version}/apifox-mcp_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "81c30641a629ecf24784c124ba3e680c321be37a6754aa54493e20c5c2f82a3f"
      url "https://github.com/iwen-conf/apifox-mcp/releases/download/v#{version}/apifox-mcp_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "cfdb5d113b947689bba652e0483acfa6fb1ffc42d13af4e32f061ba7dfc9ee99"
      url "https://github.com/iwen-conf/apifox-mcp/releases/download/v#{version}/apifox-mcp_#{version}_linux_arm64.tar.gz"
    end
  end

  name "apifox-mcp"
  desc "Go CLI for AI-authored Apifox/OpenAPI documentation"
  homepage "https://github.com/iwen-conf/apifox-mcp"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "apifox-mcp"

  # No zap stanza required

end
