# This file was generated by GoReleaser. DO NOT EDIT.
cask "apifox-cli" do
  version "1.3.0"

  on_macos do
    on_intel do
      sha256 "061f26c7e567f21806f1c5fc40110e654a2af548385ed3365ffd4b5c991a9e78"
      url "https://github.com/iwen-conf/apifox-mcp/releases/download/v#{version}/apifox-cli_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "7654ee1929c4fc62663d5852dd0a1a77d77ab6c42b03a3059302ee792d2e5225"
      url "https://github.com/iwen-conf/apifox-mcp/releases/download/v#{version}/apifox-cli_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "4ad95d3143d47ef27d3bd5a1dbd87a7171abc3cedf116d62a658d12f71b3c0b3"
      url "https://github.com/iwen-conf/apifox-mcp/releases/download/v#{version}/apifox-cli_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "0c5048b3b7544abf6aa92dae0bc55d401bf8336acc34fe277c7d56b6554d0b35"
      url "https://github.com/iwen-conf/apifox-mcp/releases/download/v#{version}/apifox-cli_#{version}_linux_arm64.tar.gz"
    end
  end

  name "apifox-cli"
  desc "Go CLI for AI-authored Apifox/OpenAPI documentation"
  homepage "https://github.com/iwen-conf/apifox-mcp"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "apifox-cli"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr",
        args: ["-d", "com.apple.quarantine", "#{staged_path}/apifox-cli"],
        sudo: false,
        must_succeed: false
    end
  end

  # No zap stanza required

end
