# This file was generated by GoReleaser. DO NOT EDIT.
cask "apifox-mcp" do
  version "1.2.2"

  on_macos do
    on_intel do
      sha256 "8d57cc714b611307896c57103ca48c141ded424c3574649010db2ba99beb93bf"
      url "https://github.com/iwen-conf/apifox-mcp/releases/download/v#{version}/apifox-mcp_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "7ffaeb4b9ccb4ac4fc7c21a1f90ad0dc3294bda68866c9bc515e007eb2f3f841"
      url "https://github.com/iwen-conf/apifox-mcp/releases/download/v#{version}/apifox-mcp_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "0f03ffa33f6cd32ff918c1632b1e0cf0ceae72e7c68309d1e9424f0dc9d869ed"
      url "https://github.com/iwen-conf/apifox-mcp/releases/download/v#{version}/apifox-mcp_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "726f2869ee36c288bf62980cd419a7fe3cb117e4e16d5f3d7c1c89695dd044ed"
      url "https://github.com/iwen-conf/apifox-mcp/releases/download/v#{version}/apifox-mcp_#{version}_linux_arm64.tar.gz"
    end
  end

  name "apifox-mcp"
  desc "Go CLI for AI-authored Apifox/OpenAPI documentation"
  homepage "https://github.com/iwen-conf/apifox-mcp"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "apifox-mcp"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr",
        args: ["-d", "com.apple.quarantine", "#{staged_path}/apifox-mcp"],
        sudo: false,
        must_succeed: false
    end
  end

  # No zap stanza required

end
