# This file was generated by GoReleaser. DO NOT EDIT.
cask "apifox-mcp" do
  version "1.2.1"

  on_macos do
    on_intel do
      sha256 "15d512baae8442a2f433f606b37220b522e8ad589e28b626ad1eadca78ef7cb4"
      url "https://github.com/iwen-conf/apifox-mcp/releases/download/v#{version}/apifox-mcp_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "1880d7f0952c2ef25d05e3b3b16810b386991eee33c5be138963dde5f395b935"
      url "https://github.com/iwen-conf/apifox-mcp/releases/download/v#{version}/apifox-mcp_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "5ee0f999eadf095711c32eaa7d058e9e8b4de9f7773b2ce6ec7a47feb9a29abd"
      url "https://github.com/iwen-conf/apifox-mcp/releases/download/v#{version}/apifox-mcp_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "f878fdc0096416b6a18ff0c6224ab192d3ed0ed0559acc7276705820687d3460"
      url "https://github.com/iwen-conf/apifox-mcp/releases/download/v#{version}/apifox-mcp_#{version}_linux_arm64.tar.gz"
    end
  end

  name "apifox-mcp"
  desc "Go CLI for AI-authored Apifox/OpenAPI documentation"
  homepage "https://github.com/iwen-conf/apifox-mcp"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "apifox-mcp"

  # No zap stanza required

end
